# 01. Data Quality

### Objectives

The purpose of this notebook is to:

- Verify dataset integrity and completeness
- Understand the dataset structure and schema
- Identify missing or duplicate records
- Validate data types and value ranges
- Detect inconsistencies and outliers
- Generate a data quality summary before Exploratory Data Analysis (EDA)

### Load all the required libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from pathlib import Path

### Load all yearly Parquet files into a single DataFrame.

In [ ]:
folder = Path("../data/raw/weather")

parquet_files = sorted(folder.rglob("*.parquet"))

data = pd.concat(
    (pd.read_parquet(file) for file in parquet_files),
    ignore_index=True
)

print(f"Files loaded: {len(parquet_files)}")
print(data.shape)

Files loaded: 6
(4802400, 30)

### Initial Check

In [3]:
data.head()

,time,dni,dhi,ghi,temperature_2m,relative_humidity_2m,rain,precipitation,wind_speed_10m,wind_direction_10m,...,surface_pressure,vapour_pressure_deficit,apparent_temperature,dew_point_2m,city,state,rank,tier,latitude,longitude
0,2021-01-01 00:00:00,0.0,0.0,0.0,23.0,75,0.0,0.0,10.2,352,...,1010.6,0.71,24.6,18.327512,Mumbai,Maharashtra,1,1,19.07283,72.88261
1,2021-01-01 01:00:00,0.0,0.0,0.0,22.8,74,0.0,0.0,7.2,360,...,1010.3,0.72,24.6,17.920775,Mumbai,Maharashtra,1,1,19.07283,72.88261
2,2021-01-01 02:00:00,0.0,0.0,0.0,22.3,77,0.0,0.0,6.2,350,...,1009.6,0.62,24.4,18.070285,Mumbai,Maharashtra,1,1,19.07283,72.88261
3,2021-01-01 03:00:00,0.0,0.0,0.0,21.8,82,0.0,0.0,4.7,351,...,1009.4,0.48,24.2,18.588126,Mumbai,Maharashtra,1,1,19.07283,72.88261
4,2021-01-01 04:00:00,0.0,0.0,0.0,21.4,84,0.0,0.0,4.7,9,...,1009.3,0.40,23.8,18.582460,Mumbai,Maharashtra,1,1,19.07283,72.88261

In [6]:
data.columns

Index(['time', 'dni', 'dhi', 'ghi', 'temperature_2m', 'relative_humidity_2m',
       'rain', 'precipitation', 'wind_speed_10m', 'wind_direction_10m',
       'wind_direction_100m', 'wind_gusts_10m', 'wind_speed_100m',
       'cloud_cover', 'sunshine_duration', 'weather_code', 'snowfall',
       'snow_depth', 'et0_fao_evapotranspiration', 'pressure_msl',
       'surface_pressure', 'vapour_pressure_deficit', 'apparent_temperature',
       'dew_point_2m', 'city', 'state', 'rank', 'tier', 'latitude',
       'longitude'],
      dtype='object')

In [8]:
data.info(show_counts=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4802400 entries, 0 to 4802399
Data columns (total 30 columns):
 #   Column                      Non-Null Count    Dtype
---  ------                      --------------    -----
 0   time                        4802400 non-null  datetime64[ns]
 1   dni                         4802400 non-null  float64
 2   dhi                         4802400 non-null  float64
 3   ghi                         4802400 non-null  float64
 4   temperature_2m              4802400 non-null  float64
 5   relative_humidity_2m        4802400 non-null  int64
 6   rain                        4802400 non-null  float64
 7   precipitation               4802400 non-null  float64
 8   wind_speed_10m              4802400 non-null  float64
 9   wind_direction_10m          4802400 non-null  int64
 10  wind_direction_100m         4802400 non-null  int64
 11  wind_gusts_10m              4802400 non-null  float64
 12  wind_speed_100m             4802400 non-null  float64
 13  cloud_cover                 4802400 non-null  int64
 14  sunshine_duration           4802400 non-null  float64
 15  weather_code                4802400 non-null  int64
 16  snowfall                    4802400 non-null  float64
 17  snow_depth                  4802400 non-null  float64
 18  et0_fao_evapotranspiration  4802400 non-null  float64
 19  pressure_msl                4802400 non-null  float64
 20  surface_pressure            4802400 non-null  float64
 21  vapour_pressure_deficit     4802400 non-null  float64
 22  apparent_temperature        4802400 non-null  float64
 23  dew_point_2m                4802400 non-null  float64
 24  city                        4802400 non-null  object
 25  state                       4802400 non-null  object
 26  rank                        4802400 non-null  int64
 27  tier                        4802400 non-null  int64
 28  latitude                    4802400 non-null  float64
 29  longitude                   4802400 non-null  float64
dtypes: datetime64[ns](1), float64(20), int64(7), object(2)
memory usage: 1.1+ GB

In [10]:
data.describe()

,time,dni,dhi,ghi,temperature_2m,relative_humidity_2m,rain,precipitation,wind_speed_10m,wind_direction_10m,...,et0_fao_evapotranspiration,pressure_msl,surface_pressure,vapour_pressure_deficit,apparent_temperature,dew_point_2m,rank,tier,latitude,longitude
count,4802400,4.802400e+06,4.802400e+06,4.802400e+06,4.802400e+06,4.802400e+06,4.802400e+06,4.802400e+06,4.802400e+06,4.802400e+06,...,4.802400e+06,4.802400e+06,4.802400e+06,4.802400e+06,4.802400e+06,4.802400e+06,4.802400e+06,4.802400e+06,4.802400e+06,4.802400e+06
mean,2023-09-28 11:29:59.999999488,2.101479e+02,7.368215e+01,2.130437e+02,2.562875e+01,6.537896e+01,1.447825e-01,1.451548e-01,9.302901e+00,1.939210e+02,...,1.885010e-01,1.008977e+03,9.802724e+02,1.380914e+00,2.754425e+01,1.719869e+01,5.050000e+01,1.790000e+00,2.197389e+01,7.809380e+01
min,2021-01-01 00:00:00,0.000000e+00,0.000000e+00,0.000000e+00,-1.490000e+01,3.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,9.794000e+02,8.275000e+02,0.000000e+00,-2.000000e+01,-2.553881e+01,1.000000e+00,1.000000e+00,8.485500e+00,7.006673e+01
25%,2022-05-16 05:45:00,0.000000e+00,0.000000e+00,0.000000e+00,2.220000e+01,4.700000e+01,0.000000e+00,0.000000e+00,5.700000e+00,9.400000e+01,...,1.000000e-02,1.004900e+03,9.648000e+02,3.800000e-01,2.300000e+01,1.188855e+01,2.575000e+01,1.000000e+00,1.859390e+01,7.476383e+01
50%,2023-09-28 11:30:00,0.000000e+00,8.000000e+00,9.000000e+00,2.610000e+01,6.900000e+01,0.000000e+00,0.000000e+00,8.400000e+00,2.200000e+02,...,8.000000e-02,1.009200e+03,9.862000e+02,9.400000e-01,2.900000e+01,1.873837e+01,5.050000e+01,2.000000e+00,2.249077e+01,7.736644e+01
75%,2025-02-09 17:15:00,4.403000e+02,1.380000e+02,4.240000e+02,2.960000e+01,8.600000e+01,0.000000e+00,0.000000e+00,1.210000e+01,2.830000e+02,...,3.300000e-01,1.013200e+03,1.002400e+03,1.930000e+00,3.300000e+01,2.317278e+01,7.525000e+01,2.250000e+00,2.652643e+01,8.019076e+01
max,2026-06-24 23:00:00,1.005100e+03,5.050000e+02,1.044000e+03,4.830000e+01,1.000000e+02,8.570000e+01,8.570000e+01,7.680000e+01,3.600000e+02,...,1.190000e+00,1.041500e+03,1.021800e+03,1.089000e+01,5.010000e+01,3.030190e+01,1.000000e+02,3.000000e+00,3.408565e+01,9.174580e+01
std,NaN,2.807573e+02,9.367467e+01,2.869622e+02,6.507994e+00,2.374022e+01,7.775817e-01,7.782395e-01,5.083550e+00,1.041691e+02,...,2.246412e-01,5.739596e+00,2.805033e+01,1.358095e+00,7.876987e+00,6.826552e+00,2.886607e+01,8.160270e-01,5.832041e+00,4.569866e+00